### Docker Compose File for the project messaging-api-oban dependencies

services:
  # app:
  #   build: .
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     - DATABASE_URL=postgres://postgres:postgres@postgres:5432/messaging
  #     - SECRET_KEY_BASE=your_secret_key_base_here
  #     - PORT=4000
  #     - FEATURES_CONFIG=/etc/app/features.yaml
  #     - S3_BUCKET=messaging-blobs
  #     - S3_REGION=us-east-1
  #   volumes:
  #     - ./config/features.yaml:/etc/app/features.yaml:ro
  #     - ./priv/storage:/app/priv/storage
  #   depends_on:
  #     - postgres
  #     - redis
  #     - s3_minio

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messaging
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  s3_minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
    volumes:
      - s3_data:/data
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin

  memcached:
    image: memcached:latest
    ports:
      - 11211:11211
    volumes:
      - memcached_data:/data
    environment:
      MEMCACHED_MAX_ITEM_SIZE: 1024
      MEMCACHED_MAX_CONNECTIONS: 1024
      MEMCACHED_MAX_CONNECTIONS_PER_CLIENT: 1024
      MEMCACHED_MAX_CONNECTIONS_PER_SERVER: 1024


volumes:
  postgres_data:
  redis_data:
  s3_data:
  memcached_data: